source "https://rubygems.org"

if ENV.key?('PUPPET_GEM_VERSION')
  gem "puppet", "#{ENV['PUPPET_GEM_VERSION']}"
end

gem "serverspec"
gem "net-ssh", "2.7"
gem "rake"
gem "rspec_junit_formatter"
gem "rspec-puppet"
gem "puppetlabs_spec_helper"
gem "librarian-puppet", "1.3.2"
gem "parallel_tests", "2.9.0"
gem "safe_yaml"
