require 'rake'
require 'rspec/core/rake_task'
require 'puppetlabs_spec_helper/rake_tasks'

exclude_paths = [
  "vendor/**/*",
  "spec/**/*",
  "tests/**/*",
]

begin
  if Gem::Specification::find_by_name('puppet-lint')
    require 'puppet-lint/tasks/puppet-lint'
    PuppetLint.configuration.ignore_paths = exclude_paths
    PuppetLint.configuration.send("disable_80chars")
    PuppetLint.configuration.send("disable_hard_tabs")
    PuppetLint.configuration.send("disable_2sp_soft_tabs")
    PuppetLint.configuration.log_format = "%{path}:%{line}:%{check}:%{KIND}:%{message}"
    PuppetLint.configuration.fail_on_warnings = true
     
    # Forsake support for Puppet 2.6.2 for the benefit of cleaner code.
    # http://puppet-lint.com/checks/class_parameter_defaults/
    PuppetLint.configuration.send('disable_class_parameter_defaults')
    # http://puppet-lint.com/checks/class_inherits_from_params_class/
    PuppetLint.configuration.send('disable_class_inherits_from_params_class')
    task :default => [:lint, :spec]
  end
  if Gem::Specification::find_by_name('puppet-syntax')
    require 'puppet-syntax/tasks/puppet-syntax'
    PuppetSyntax.exclude_paths = exclude_paths
    task :test => [:lint, :syntax, :spec]
  end
rescue Gem::LoadError
end
